//! Machine-readable deployment release manifest (schema v1).
//!
//! Generated by the release pipeline (`scripts/build-release.sh` / CI), never
//! handwritten. One schema serves both channels (`channel` field differs);
//! no incompatible dev-only format exists. Validation fails closed.

use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;

use super::artifact::is_supported_target;
use super::channel::DeploymentChannel;
use crate::release::integrity::validate_artifact_name;

/// One artifact entry in a deployment manifest.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManifestArtifact {
    pub target: String,
    pub filename: String,
    pub sha256: String,
    pub size: u64,
    pub build_id: String,
    pub commit: String,
}

/// Deployment manifest schema v1.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeploymentManifest {
    pub schema_version: u32,
    pub version: String,
    pub channel: DeploymentChannel,
    pub build_id: Option<String>,
    pub commit: Option<String>,
    pub artifacts: Vec<ManifestArtifact>,
}

/// Typed manifest failures.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum DeploymentManifestError {
    #[error("deployment manifest error: {0}")]
    Schema(String),
    #[error("deployment manifest error: duplicate target '{0}'")]
    DuplicateTarget(String),
}

impl DeploymentManifest {
    pub fn parse_json(doc: &str) -> Result<Self, DeploymentManifestError> {
        serde_json::from_str(doc)
            .map_err(|e| DeploymentManifestError::Schema(format!("malformed manifest: {e}")))
    }

    pub fn to_canonical_json(&self) -> Result<String, DeploymentManifestError> {
        let mut clone = self.clone();
        clone.artifacts.sort_by(|a, b| a.target.cmp(&b.target));
        serde_json::to_string_pretty(&clone)
            .map_err(|e| DeploymentManifestError::Schema(format!("serialization failed: {e}")))
    }

    /// Fail-closed validation: schema version, semver, channel coherence,
    /// non-empty artifacts, safe filenames, checksums, unique + supported
    /// targets, consistent build IDs, commit metadata present.
    pub fn validate(&self) -> Result<(), DeploymentManifestError> {
        let bad = |m: String| DeploymentManifestError::Schema(m);
        if self.schema_version != 1 {
            return Err(bad(format!(
                "unsupported schema_version {}",
                self.schema_version
            )));
        }
        if self.version.trim().is_empty() {
            return Err(bad("version is empty".to_string()));
        }
        if semver::Version::parse(self.version.trim()).is_err() {
            return Err(bad("version is not valid semver".to_string()));
        }
        if self.artifacts.is_empty() {
            return Err(bad("manifest lists zero artifacts".to_string()));
        }
        // Channel is typed (serde rejects unknown channels at parse time).
        let mut seen_targets = BTreeSet::new();
        let mut build_ids = BTreeSet::new();
        for a in &self.artifacts {
            if a.target.trim().is_empty() {
                return Err(bad("artifact target is empty".to_string()));
            }
            if !is_supported_target(&a.target) {
                return Err(bad(format!("invalid target '{}'", a.target)));
            }
            if !seen_targets.insert(a.target.clone()) {
                return Err(DeploymentManifestError::DuplicateTarget(a.target.clone()));
            }
            validate_artifact_name(&a.filename)
                .map_err(|_| bad(format!("unsafe filename '{}'", a.filename)))?;
            if a.sha256.len() != 64 || !a.sha256.chars().all(|c| c.is_ascii_hexdigit()) {
                return Err(bad(format!(
                    "artifact '{}' has malformed sha256",
                    a.filename
                )));
            }
            if a.build_id.trim().is_empty() {
                return Err(bad(format!(
                    "artifact '{}' is missing build_id",
                    a.filename
                )));
            }
            if a.commit.trim().is_empty() {
                return Err(bad(format!(
                    "artifact '{}' is missing commit metadata",
                    a.filename
                )));
            }
            build_ids.insert(a.build_id.clone());
        }
        // Manifest-level build_id, when present, must agree with artifacts.
        if let Some(ref bid) = self.build_id {
            if bid.trim().is_empty() {
                return Err(bad("manifest build_id is empty".to_string()));
            }
            if build_ids.len() == 1 && !build_ids.contains(bid) {
                return Err(bad(
                    "manifest build_id is inconsistent with artifacts".to_string()
                ));
            }
        }
        if let Some(ref c) = self.commit {
            if c.trim().is_empty() {
                return Err(bad("manifest commit is empty".to_string()));
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> DeploymentManifest {
        DeploymentManifest {
            schema_version: 1,
            version: "0.1.1".to_string(),
            channel: DeploymentChannel::Production,
            build_id: Some("0123456789abcdef".to_string()),
            commit: Some("abc123".to_string()),
            artifacts: vec![ManifestArtifact {
                target: "x86_64-unknown-linux-gnu".to_string(),
                filename: "m31a-linux-x64.tar.gz".to_string(),
                sha256: "a".repeat(64),
                size: 100,
                build_id: "0123456789abcdef".to_string(),
                commit: "abc123".to_string(),
            }],
        }
    }

    #[test]
    fn valid_manifest_passes() {
        assert!(sample().validate().is_ok());
        let doc = sample().to_canonical_json().unwrap();
        let back = DeploymentManifest::parse_json(&doc).unwrap();
        assert_eq!(back, sample());
    }

    #[test]
    fn dev_manifest_uses_same_schema() {
        let mut m = sample();
        m.channel = DeploymentChannel::Development;
        assert!(m.validate().is_ok());
    }

    #[test]
    fn rejects_malformed() {
        let mut m = sample();
        m.version = String::new();
        assert!(m.validate().is_err());
        let mut m = sample();
        m.version = "nope".to_string();
        assert!(m.validate().is_err());
        let mut m = sample();
        m.artifacts.clear();
        assert!(m.validate().is_err());
        let mut m = sample();
        m.artifacts[0].sha256 = "short".to_string();
        assert!(m.validate().is_err());
        let mut m = sample();
        m.artifacts.push(m.artifacts[0].clone());
        assert!(matches!(
            m.validate(),
            Err(DeploymentManifestError::DuplicateTarget(_))
        ));
        let mut m = sample();
        m.artifacts[0].target = "bogus-target".to_string();
        assert!(m.validate().is_err());
        let mut m = sample();
        m.artifacts[0].build_id = String::new();
        assert!(m.validate().is_err());
        let mut m = sample();
        m.artifacts[0].commit = String::new();
        assert!(m.validate().is_err());
        assert!(DeploymentManifest::parse_json("{}").is_err());
        assert!(
            DeploymentManifest::parse_json(
                r#"{"schema_version":1,"version":"0.1.1","channel":"canary","artifacts":[]}"#
            )
            .is_err()
        );
    }
}
