run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosimple

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
