version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - shadow

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

issues:
  rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
