package tui

import (
	"fmt"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/bubbles/viewport"
	"github.com/charmbracelet/lipgloss"
	"github.com/eshanized/M31A/internal/tui/components"
	"github.com/eshanized/M31A/internal/tui/theme"
	"github.com/eshanized/M31A/internal/types"
)

// PlanModel displays the plan generated by the Plan phase and lets the
// user review tasks before execution begins.
type PlanModel struct {
	tasks        []types.Task
	theme        theme.Theme
	modelID      string
	modelName    string
	provider     string
	estCost      float64
	costEstimate string
	sessionID    string
	width        int
	height       int
	viewport     viewport.Model
	selected     int
	// Pre-computed wave groupings for visual display
	waves [][]types.Task
}

// NewPlanModel creates a PlanModel.
func NewPlanModel(
	tasks []types.Task,
	t theme.Theme,
	modelID, modelName, provider string,
	estCost float64,
	costEstimate string,
	w, h int,
) *PlanModel {
	pm := &PlanModel{
		tasks:        tasks,
		theme:        t,
		modelID:      modelID,
		modelName:    modelName,
		provider:     provider,
		estCost:      estCost,
		costEstimate: costEstimate,
		width:        w,
		height:       h,
	}
	pm.computeWaves()
	pm.initViewport()
	return pm
}

// computeWaves groups tasks into topological layers for visual display.
// Tasks with no dependencies form wave 0, and each subsequent wave
// contains tasks whose dependencies are all in earlier waves.
func (pm *PlanModel) computeWaves() {
	if len(pm.tasks) == 0 {
		pm.waves = nil
		return
	}

	// Build task ID → index map
	idToIdx := make(map[int]int, len(pm.tasks))
	for i, t := range pm.tasks {
		idToIdx[t.ID] = i
	}

	// Compute wave for each task via topological layering
	waveOf := make([]int, len(pm.tasks))
	for i := range waveOf {
		waveOf[i] = -1
	}

	// Iteratively assign waves until all tasks have one
	remaining := len(pm.tasks)
	for remaining > 0 {
		for i, t := range pm.tasks {
			if waveOf[i] >= 0 {
				continue
			}
			if len(t.Dependencies) == 0 {
				waveOf[i] = 0
				remaining--
				continue
			}
			maxDepWave := -1
			allResolved := true
			for _, depID := range t.Dependencies {
				depIdx, ok := idToIdx[depID]
				if !ok {
					continue // dep not in this set — treat as resolved
				}
				if waveOf[depIdx] < 0 {
					allResolved = false
					break
				}
				if waveOf[depIdx] > maxDepWave {
					maxDepWave = waveOf[depIdx]
				}
			}
			if allResolved {
				if maxDepWave >= 0 {
					waveOf[i] = maxDepWave + 1
				} else {
					waveOf[i] = 0
				}
				remaining--
			}
		}
	}

	// Group tasks into wave slices
	maxWave := 0
	for _, w := range waveOf {
		if w > maxWave {
			maxWave = w
		}
	}
	pm.waves = make([][]types.Task, maxWave+1)
	for i, t := range pm.tasks {
		w := waveOf[i]
		if w < 0 {
			w = 0
		}
		pm.waves[w] = append(pm.waves[w], t)
	}
}

// UpdateTasks replaces the task list and recomputes waves.
func (pm *PlanModel) UpdateTasks(tasks []types.Task) {
	pm.tasks = tasks
	pm.computeWaves()
	pm.viewport.SetContent(pm.renderTasks())
}

// SetDimensions updates the plan model dimensions.
func (pm *PlanModel) SetDimensions(w, h int) {
	pm.width = w
	pm.height = h
	pm.initViewport()
}

func (pm *PlanModel) initViewport() {
	h := pm.height - 5 // leave room for header, divider, footer
	if h < 5 {
		h = 5
	}
	pm.viewport = viewport.New(pm.width, h)
	pm.viewport.SetContent(pm.renderTasks())
}

// Update handles plan screen key events.
func (pm *PlanModel) Update(msg tea.Msg) (*PlanModel, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "j", "down":
			pm.viewport.LineDown(1)
		case "k", "up":
			pm.viewport.LineUp(1)
		case "enter", " ":
			// Approve plan → transition to execute
			return pm, func() tea.Msg {
				return AppMsg{Screen: ScreenExecute}
			}
		case "esc", "q":
			return pm, func() tea.Msg {
				return AppMsg{Screen: ScreenREPL}
			}
		}
	}
	return pm, nil
}

// View renders the plan review screen.
func (pm *PlanModel) View() string {
	t := pm.theme
	w := pm.width

	// Header: 📋 Plan · N tasks · ~$0.0042 · model [OR]
	header := renderPlanHeader(t, len(pm.tasks), pm.estCost, pm.costEstimate, pm.modelName, pm.provider)

	divider := components.SectionDivider{
		Width: w,
		Theme: t,
	}.Render()

	// Content area
	content := pm.viewport.View()
	if len(pm.tasks) == 0 {
		content = lipgloss.NewStyle().
			Foreground(t.TextMuted).
			Width(w).
			Align(lipgloss.Center).
			Render("No tasks generated yet")
	}

	// Footer (0 padding — footer hints are flush left, last line)
	footer := lipgloss.NewStyle().
		Foreground(t.TextMuted).
		Render("↵ approve  j/k scroll  q back  o optimize")

	return lipgloss.JoinVertical(lipgloss.Left,
		header,
		divider,
		content,
		divider,
		footer,
	)
}

// waveColor returns the theme color for a given wave index.
// Wave 0 uses brand, Wave 1 uses info/secondary, higher waves use muted.
func (pm *PlanModel) waveColor(waveIdx int) lipgloss.Color {
	t := pm.theme
	switch waveIdx {
	case 0:
		return t.Brand
	case 1:
		return t.Info
	default:
		return t.TextMuted
	}
}

// renderTasks renders the full task list grouped by wave.
func (pm *PlanModel) renderTasks() string {
	t := pm.theme
	if len(pm.tasks) == 0 {
		return ""
	}

	var lines []string

	// Render each wave group
	for waveIdx, wave := range pm.waves {
		color := pm.waveColor(waveIdx)
		badgeType := components.BadgeNeutral
		switch waveIdx {
		case 0:
			badgeType = components.BadgeBrand
		case 1:
			badgeType = components.BadgeInfo
		default:
			badgeType = components.BadgeNeutral
		}
		badge := components.SimpleBadge{
			Text:    fmt.Sprintf("Wave %d — %s", waveIdx+1, waveTitle(waveIdx)),
			Type:    badgeType,
			Compact: true,
			Theme:   t,
		}
		sectionHeader := "  " + badge.Render()
		lines = append(lines, "", sectionHeader)

		for _, task := range wave {
			iconColor := color
			icon := lipgloss.NewStyle().Foreground(iconColor).Render("○")
			action := lipgloss.NewStyle().Foreground(t.Text).Bold(true).Render(task.Action)

			// Description (truncated to available width)
			desc := ""
			if task.Description != "" {
				maxDescLen := pm.width - 20
				if maxDescLen < 20 {
					maxDescLen = 20
				}
				descText := TruncateEnd(task.Description, maxDescLen)
				desc = " " + lipgloss.NewStyle().Foreground(t.TextSecondary).Render("— "+descText)
			}

			// Dependency arrows
			depStr := ""
			if len(task.Dependencies) > 0 {
				var depIDs []string
				for _, d := range task.Dependencies {
					depIDs = append(depIDs, fmt.Sprintf("task-%d", d))
				}
				depStr = " " + lipgloss.NewStyle().Foreground(t.TextMuted).Render("⇢ "+strings.Join(depIDs, ", "))
			}

			line := fmt.Sprintf("    %s %s%s%s", icon, action, desc, depStr)
			lines = append(lines, line)
		}
	}

	return strings.Join(lines, "\n")
}

// waveTitle returns a descriptive title for a wave based on its index.
func waveTitle(idx int) string {
	titles := []string{
		"Foundation",
		"Core Features",
		"Integration",
		"Polish",
		"Verification",
	}
	if idx < len(titles) {
		return titles[idx]
	}
	return fmt.Sprintf("Phase %d", idx+1)
}
