package tui

import (
	"fmt"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/bubbles/viewport"
	"github.com/charmbracelet/lipgloss"
	"github.com/eshanized/M31A/internal/tui/theme"
	"github.com/eshanized/M31A/internal/types"
)

// PlanModel displays the plan generated by the Plan phase and lets the
// user review tasks before execution begins.
type PlanModel struct {
	tasks        []types.Task
	theme        theme.Theme
	modelID      string
	modelName    string
	provider     string
	estCost      float64
	costEstimate string
	sessionID    string
	width        int
	height       int
	viewport     viewport.Model
	selected     int
}

// NewPlanModel creates a PlanModel.
func NewPlanModel(
	tasks []types.Task,
	t theme.Theme,
	modelID, modelName, provider string,
	estCost float64,
	costEstimate string,
	w, h int,
) *PlanModel {
	pm := &PlanModel{
		tasks:        tasks,
		theme:        t,
		modelID:      modelID,
		modelName:    modelName,
		provider:     provider,
		estCost:      estCost,
		costEstimate: costEstimate,
		width:        w,
		height:       h,
	}
	pm.initViewport()
	return pm
}

func (pm *PlanModel) initViewport() {
	h := pm.height - 6 // leave room for header and footer
	if h < 5 {
		h = 5
	}
	pm.viewport = viewport.New(pm.width, h)
	pm.viewport.SetContent(pm.renderTasks())
}

// UpdateTasks replaces the task list.
func (pm *PlanModel) UpdateTasks(tasks []types.Task) {
	pm.tasks = tasks
	pm.viewport.SetContent(pm.renderTasks())
}

// SetDimensions updates the plan model dimensions.
func (pm *PlanModel) SetDimensions(w, h int) {
	pm.width = w
	pm.height = h
	pm.initViewport()
}

// Update handles plan screen key events.
func (pm *PlanModel) Update(msg tea.Msg) (*PlanModel, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "j", "down":
			pm.viewport.LineDown(1)
		case "k", "up":
			pm.viewport.LineUp(1)
		case "enter", " ":
			// Approve plan → transition to execute
			return pm, func() tea.Msg {
				return AppMsg{Screen: ScreenExecute}
			}
		case "esc", "q":
			return pm, func() tea.Msg {
				return AppMsg{Screen: ScreenREPL}
			}
		}
	}
	return pm, nil
}

// View renders the plan review screen.
func (pm *PlanModel) View() string {
	t := pm.theme
	w := pm.width

	// Header
	title := lipgloss.NewStyle().
		Foreground(t.Brand).
		Bold(true).
		PaddingLeft(2).
		Render(fmt.Sprintf("📋  Plan — %d tasks", len(pm.tasks)))

	if pm.estCost > 0 {
		cost := lipgloss.NewStyle().Foreground(t.Warning).Render(fmt.Sprintf("~$%.4f", pm.estCost))
		title = title + "  " + cost
	} else if pm.costEstimate != "" {
		cost := lipgloss.NewStyle().Foreground(t.Warning).Render(pm.costEstimate)
		title = title + "  " + cost
	}

	// Model badge
	badge := ""
	if pm.modelName != "" {
		badge = lipgloss.NewStyle().Foreground(t.TextMuted).
			Render("  " + pm.modelName + " [" + ProviderShortName(pm.provider) + "]")
	}

	divider := lipgloss.NewStyle().Foreground(t.TextMuted).
		Render(strings.Repeat("─", w))

	// Footer
	footer := lipgloss.NewStyle().Foreground(t.TextMuted).PaddingLeft(2).
		Render("↵ approve  q back  j/k scroll")

	return lipgloss.JoinVertical(lipgloss.Left,
		title+badge,
		divider,
		pm.viewport.View(),
		divider,
		footer,
	)
}

func (pm *PlanModel) renderTasks() string {
	t := pm.theme
	var lines []string
	for i, task := range pm.tasks {
		num := lipgloss.NewStyle().Foreground(t.TextMuted).Render(fmt.Sprintf("%3d.", i+1))
		action := lipgloss.NewStyle().Foreground(t.Text).Bold(true).Render(task.Action)
		var desc string
		if task.Description != "" {
			desc = "\n     " + lipgloss.NewStyle().Foreground(t.TextSecondary).Render(task.Description)
		}
		lines = append(lines, "  "+num+" "+action+desc)
		if i < len(pm.tasks)-1 {
			lines = append(lines, "")
		}
	}
	return strings.Join(lines, "\n")
}
