package tui

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/bubbles/viewport"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/eshanized/M31A/internal/tui/components"
	"github.com/eshanized/M31A/internal/tui/theme"
	"github.com/eshanized/M31A/internal/types"
)

// PlanModel displays the plan generated by the Plan phase and lets the
// user review tasks before execution begins. Supports refine and confirm modes.
type PlanModel struct {
	tasks        []types.Task
	theme        theme.Theme
	modelID      string
	modelName    string
	provider     string
	estCost      float64
	costEstimate string
	timeEstimate string
	sessionID    string
	width        int
	height       int
	viewport     viewport.Model
	// Pre-computed wave groupings for visual display
	waves [][]types.Task
	// Rich plan content (markdown) for review
	planContent string
	planVersion int
	// Mode flags
	confirmMode bool
	refineMode  bool
	refineInput *PlanRefineModel
}

// NewPlanModel creates a PlanModel.
func NewPlanModel(
	tasks []types.Task,
	t theme.Theme,
	modelID, modelName, provider string,
	estCost float64,
	costEstimate string,
	w, h int,
) *PlanModel {
	pm := &PlanModel{
		tasks:        tasks,
		theme:        t,
		modelID:      modelID,
		modelName:    modelName,
		provider:     provider,
		estCost:      estCost,
		costEstimate: costEstimate,
		width:        w,
		height:       h,
	}
	pm.computeWaves()
	pm.initViewport()
	return pm
}

// SetPlanContent sets the rich markdown plan content for display.
func (pm *PlanModel) SetPlanContent(markdown string) {
	pm.planContent = markdown
	if markdown != "" {
		pm.viewport.SetContent(markdown)
	}
}

// SetPlanVersion sets the plan version number for display.
func (pm *PlanModel) SetPlanVersion(version int) {
	pm.planVersion = version
}

// computeWaves groups tasks into topological layers for visual display.
func (pm *PlanModel) computeWaves() {
	if len(pm.tasks) == 0 {
		pm.waves = nil
		return
	}

	idToIdx := make(map[int]int, len(pm.tasks))
	for i, t := range pm.tasks {
		idToIdx[t.ID] = i
	}

	waveOf := make([]int, len(pm.tasks))
	for i := range waveOf {
		waveOf[i] = -1
	}

	remaining := len(pm.tasks)
	for remaining > 0 {
		assigned := 0
		for i, t := range pm.tasks {
			if waveOf[i] >= 0 {
				continue
			}
			if len(t.Dependencies) == 0 {
				waveOf[i] = 0
				remaining--
				assigned++
				continue
			}
			maxDepWave := -1
			allResolved := true
			for _, depID := range t.Dependencies {
				depIdx, ok := idToIdx[depID]
				if !ok {
					continue
				}
				if waveOf[depIdx] < 0 {
					allResolved = false
					break
				}
				if waveOf[depIdx] > maxDepWave {
					maxDepWave = waveOf[depIdx]
				}
			}
			if allResolved {
				if maxDepWave >= 0 {
					waveOf[i] = maxDepWave + 1
				} else {
					waveOf[i] = 0
				}
				remaining--
				assigned++
			}
		}
		if assigned == 0 {
			for i := range pm.tasks {
				if waveOf[i] < 0 {
					waveOf[i] = 0
					remaining--
				}
			}
			break
		}
	}

	maxWave := 0
	for _, w := range waveOf {
		if w > maxWave {
			maxWave = w
		}
	}
	pm.waves = make([][]types.Task, maxWave+1)
	for i, t := range pm.tasks {
		w := waveOf[i]
		if w < 0 {
			w = 0
		}
		pm.waves[w] = append(pm.waves[w], t)
	}
}

// UpdateTasks replaces the task list and recomputes waves.
func (pm *PlanModel) UpdateTasks(tasks []types.Task) {
	pm.tasks = tasks
	pm.computeWaves()
	if pm.planContent == "" {
		pm.viewport.SetContent(pm.renderTasks())
	}
}

// SetDimensions updates the plan model dimensions.
func (pm *PlanModel) SetDimensions(w, h int) {
	pm.width = w
	pm.height = h
	pm.initViewport()
}

// SetTheme updates the theme.
func (pm *PlanModel) SetTheme(t theme.Theme) {
	pm.theme = t
}

// Init implements Screenable.
func (pm *PlanModel) Init() tea.Cmd {
	return nil
}

func (pm *PlanModel) initViewport() {
	h := pm.height - 7
	if h < 5 {
		h = 5
	}
	pm.viewport = viewport.New(pm.width, h)
	if pm.planContent != "" {
		pm.viewport.SetContent(pm.planContent)
	} else {
		pm.viewport.SetContent(pm.renderTasks())
	}
}

// Update handles plan screen key events.
func (pm *PlanModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	if pm.refineMode && pm.refineInput != nil {
		return pm.handleRefineUpdate(msg)
	}

	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		pm.width = msg.Width
		pm.height = msg.Height
		pm.initViewport()
	case tea.MouseMsg:
		if msg.Action == tea.MouseActionPress {
			switch msg.Button {
			case tea.MouseButtonWheelUp:
				pm.viewport.LineUp(3)
			case tea.MouseButtonWheelDown:
				pm.viewport.LineDown(3)
			}
		}
	case tea.KeyMsg:
		if pm.confirmMode {
			return pm.handleConfirmKey(msg)
		}
		switch msg.String() {
		case "j", "down":
			pm.viewport.LineDown(1)
		case "k", "up":
			pm.viewport.LineUp(1)
		case "enter":
			pm.confirmMode = true
			return pm, nil
		case "r":
			pm.refineMode = true
			pm.refineInput = NewPlanRefineModel(pm.theme, pm.width)
			return pm, nil
		case "esc", "q":
			return pm, func() tea.Msg {
				return PopScreenMsg{}
			}
		}
	}
	return pm, nil
}

func (pm *PlanModel) handleConfirmKey(msg tea.KeyMsg) (tea.Model, tea.Cmd) {
	switch msg.String() {
	case "y", "Y":
		pm.confirmMode = false
		return pm, func() tea.Msg {
			return PlanApproveMsg{}
		}
	case "r":
		pm.confirmMode = false
		pm.refineMode = true
		pm.refineInput = NewPlanRefineModel(pm.theme, pm.width)
		return pm, nil
	case "esc", "n", "N":
		pm.confirmMode = false
		return pm, nil
	}
	return pm, nil
}

func (pm *PlanModel) handleRefineUpdate(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "esc":
			pm.refineMode = false
			pm.refineInput = nil
			return pm, nil
		case "ctrl+enter":
			feedback := pm.refineInput.Value()
			pm.refineMode = false
			pm.refineInput = nil
			if feedback != "" {
				return pm, func() tea.Msg {
					return PlanRefineMsg{Feedback: feedback}
				}
			}
			return pm, nil
		}
	}
	if pm.refineInput != nil {
		newRefine, cmd := pm.refineInput.Update(msg)
		if nr, ok := newRefine.(*PlanRefineModel); ok {
			pm.refineInput = nr
		}
		return pm, cmd
	}
	return pm, nil
}

// View renders the plan review screen content.
func (pm *PlanModel) View() string {
	if pm.refineMode && pm.refineInput != nil {
		return pm.refineInput.View()
	}

	content := pm.viewport.View()
	if len(pm.tasks) == 0 && pm.planContent == "" {
		content = lipgloss.NewStyle().
			Foreground(pm.theme.TextMuted).
			Width(pm.width).
			Align(lipgloss.Center).
			Render("No tasks generated yet")
	}

	footer := renderPlanFooter(pm.theme, pm.confirmMode, pm.refineMode, pm.planVersion)
	return lipgloss.JoinVertical(lipgloss.Left, content, footer)
}

func (pm *PlanModel) waveColor(waveIdx int) lipgloss.Color {
	t := pm.theme
	switch waveIdx {
	case 0:
		return t.Brand
	case 1:
		return t.Info
	default:
		return t.TextMuted
	}
}

func (pm *PlanModel) renderTasks() string {
	t := pm.theme
	if len(pm.tasks) == 0 {
		return ""
	}

	var lines []string

	for waveIdx, wave := range pm.waves {
		color := pm.waveColor(waveIdx)
		var badgeType components.BadgeType
		switch waveIdx {
		case 0:
			badgeType = components.BadgeBrand
		case 1:
			badgeType = components.BadgeInfo
		default:
			badgeType = components.BadgeNeutral
		}
		badge := components.SimpleBadge{
			Text:    fmt.Sprintf("Wave %d — %s", waveIdx+1, waveTitle(waveIdx)),
			Type:    badgeType,
			Compact: true,
			Theme:   t,
		}
		sectionHeader := "  " + badge.Render()
		lines = append(lines, "", sectionHeader)

		for _, task := range wave {
			iconColor := color
			icon := lipgloss.NewStyle().Foreground(iconColor).Render("○")
			action := lipgloss.NewStyle().Foreground(t.Text).Bold(true).Render(task.Action)

			desc := ""
			if task.Description != "" {
				maxDescLen := pm.width - 20
				if maxDescLen < 20 {
					maxDescLen = 20
				}
				descText := TruncateEnd(task.Description, maxDescLen)
				desc = " " + lipgloss.NewStyle().Foreground(t.TextSecondary).Render("— "+descText)
			}

			depStr := ""
			if len(task.Dependencies) > 0 {
				var depIDs []string
				for _, d := range task.Dependencies {
					depIDs = append(depIDs, fmt.Sprintf("task-%d", d))
				}
				depStr = " " + lipgloss.NewStyle().Foreground(t.TextMuted).Render("⇢ "+strings.Join(depIDs, ", "))
			}

			line := fmt.Sprintf("    %s %s%s%s", icon, action, desc, depStr)
			lines = append(lines, line)
		}
	}

	return strings.Join(lines, "\n")
}

func waveTitle(idx int) string {
	titles := []string{
		"Foundation",
		"Core Features",
		"Integration",
		"Polish",
		"Verification",
	}
	if idx < len(titles) {
		return titles[idx]
	}
	return fmt.Sprintf("Phase %d", idx+1)
}
