//! Canonical Action/Outcome Protocol (Issue 21, ACT-01..04).
//!
//! "The model proposes. The runtime decides."
//!
//! Provides the strongly typed runtime protocol bridging:
//! - Model proposals
//! - AgentEngine / WorkerRunner
//! - Task scheduler
//! - Workflow execution
//! - Tool governance and sandbox
//! - Verification hierarchy
//! - Telemetry and TUI projection

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

use crate::agent::supervisor::AgentOutcome;
use crate::ids::{AgentId, TaskId};
use crate::state_machine::agent::AgentRole;

/// Granular user option presented during an interactive decision point.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionUserOption {
    pub id: String,
    pub label: String,
    pub description: Option<String>,
}

/// Diagnostic summary entry associated with an action observation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DiagnosticRecord {
    pub tool: String,
    pub file: Option<String>,
    pub line: Option<usize>,
    pub column: Option<usize>,
    pub severity: String,
    pub code: Option<String>,
    pub message: String,
    pub suggested_fix: Option<String>,
}

/// Canonical typed runtime actions proposed by agents or interactive commands (Issue 21).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "action_type", content = "payload", rename_all = "snake_case")]
pub enum AgentAction {
    /// Execute a governed tool through the 11-stage pipeline.
    CallTool {
        tool_name: String,
        parameters: serde_json::Value,
    },
    /// Write or update a file within the workspace.
    WriteChange {
        path: PathBuf,
        content: String,
        description: Option<String>,
    },
    /// Run verification tier checks against workspace state.
    RunVerification {
        tier: Option<u8>,
        target: Option<String>,
    },
    /// Ask operator for semantic clarification with options.
    AskUser {
        question: String,
        options: Vec<ActionUserOption>,
    },
    /// Request operator policy approval for a privileged operation.
    RequestApproval {
        tool_name: String,
        parameters: serde_json::Value,
        risk: Option<String>,
        reason: String,
    },
    /// Introduce a new formed task into the active task graph.
    CreateTask {
        title: String,
        description: String,
        role: Option<AgentRole>,
        dependencies: Vec<TaskId>,
    },
    /// Invalidate/supersede a stale task with causal reason.
    SupersedeTask { task_id: TaskId, reason: String },
    /// Request adaptive replanning of remaining work.
    Replan {
        reason: String,
        tasks_to_supersede: Vec<TaskId>,
        new_tasks: Vec<String>,
    },
    /// Delegate work to a child agent under role boundary.
    Delegate {
        target_role: AgentRole,
        task_id: Option<TaskId>,
        reason: String,
        inputs: Vec<String>,
    },
    /// Pause active execution.
    Pause { reason: String },
    /// Resume paused execution.
    Resume { reason: Option<String> },
    /// Cancel active in-flight work.
    Cancel { reason: String },
    /// Declare task completion with verified evidence.
    Complete { summary: String },
    /// Declare task failure with diagnostic error classification.
    Fail { error: String },
}

impl AgentAction {
    /// Canonical action kind name for telemetry, auditing, and events.
    pub fn name(&self) -> &'static str {
        match self {
            Self::CallTool { .. } => "call_tool",
            Self::WriteChange { .. } => "write_change",
            Self::RunVerification { .. } => "run_verification",
            Self::AskUser { .. } => "ask_user",
            Self::RequestApproval { .. } => "request_approval",
            Self::CreateTask { .. } => "create_task",
            Self::SupersedeTask { .. } => "supersede_task",
            Self::Replan { .. } => "replan",
            Self::Delegate { .. } => "delegate",
            Self::Pause { .. } => "pause",
            Self::Resume { .. } => "resume",
            Self::Cancel { .. } => "cancel",
            Self::Complete { .. } => "complete",
            Self::Fail { .. } => "fail",
        }
    }
}

/// Canonical typed runtime observations generated by authorities after action execution (Issue 21).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "observation_type",
    content = "payload",
    rename_all = "snake_case"
)]
pub enum AgentObservation {
    /// Output produced by tool pipeline execution.
    ToolOutput {
        tool_name: String,
        call_id: String,
        output: String,
        success: bool,
        duration_ms: u64,
    },
    /// File written or updated with content-addressed hash.
    ChangeWritten {
        path: PathBuf,
        bytes_written: usize,
        content_hash: String,
    },
    /// Verification hierarchy evaluation outcome.
    VerificationResult {
        passed: bool,
        summary: String,
        tier: u8,
        diagnostics: Vec<DiagnosticRecord>,
    },
    /// User provided answer to an outstanding question.
    UserResponse { answer: String },
    /// Operator granted or denied an approval request.
    ApprovalResult {
        approved: bool,
        reason: Option<String>,
    },
    /// Task was registered in the task graph.
    TaskCreated { task_id: TaskId },
    /// Task was marked superseded.
    TaskSuperseded { task_id: TaskId },
    /// Replan was applied and persisted.
    ReplanCompleted {
        new_plan_revision: u32,
        superseded_count: usize,
        added_count: usize,
    },
    /// Subagent execution completed or failed.
    DelegationResult {
        child_agent_id: AgentId,
        outcome: Box<AgentOutcome>,
    },
    /// Execution was successfully paused.
    Paused,
    /// Execution was resumed.
    Resumed,
    /// Execution was cancelled.
    Cancelled { reason: String },
    /// Completion was validated and committed.
    Completed { summary: String },
    /// Failure was recorded and classified.
    Failed {
        error: String,
        classification: Option<String>,
    },
}

/// Durable execution record linking an action proposal to its authoritative outcome.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ActionExecutionRecord {
    pub action_id: String,
    pub action: AgentAction,
    pub observation: AgentObservation,
    pub started_at: DateTime<Utc>,
    pub completed_at: DateTime<Utc>,
    pub success: bool,
    pub policy_decision: Option<String>,
    pub correlation_id: Option<String>,
}
