package types

import "time"

// Plan represents a rich implementation plan generated by the Plan phase.
// It contains human-readable sections describing the approach, proposed changes,
// open questions, and verification strategy, along with the machine-parseable
// task list extracted from the document.
type Plan struct {
	Title           string                `json:"title"`
	Summary         string                `json:"summary"`
	ReviewNotes     []ReviewNote          `json:"review_notes,omitempty"`
	OpenQuestions   []OpenQuestion        `json:"open_questions,omitempty"`
	ProposedChanges []ProposedChangeGroup `json:"proposed_changes,omitempty"`
	Verification    VerificationPlan      `json:"verification_plan"`
	Tasks           []Task                `json:"tasks"`
	Version         int                   `json:"version"`
	RawMarkdown     string                `json:"raw_markdown"`
	CreatedAt       time.Time             `json:"created_at"`
}

// ReviewNote represents a "User Review Required" callout in the plan.
// Level is typically "IMPORTANT" or "WARNING".
type ReviewNote struct {
	Level string `json:"level"`
	Text  string `json:"text"`
}

// OpenQuestion represents a question the plan raises for the user,
// optionally with a suggested default answer.
type OpenQuestion struct {
	Question   string `json:"question"`
	Suggestion string `json:"suggestion,omitempty"`
}

// ProposedChangeGroup groups related file changes under a category heading
// (e.g., "Setup & Configuration", "Core Components").
type ProposedChangeGroup struct {
	Category string           `json:"category"`
	Changes  []ProposedChange `json:"changes"`
}

// ProposedChange describes a single file to create or modify, with a
// human-readable description of what the change accomplishes.
type ProposedChange struct {
	Action      string `json:"action"` // "NEW" or "MODIFY"
	File        string `json:"file"`
	Description string `json:"description"`
}

// VerificationPlan describes how the implementation will be validated.
// Automated steps are run programmatically; manual steps require user action.
type VerificationPlan struct {
	Automated []string `json:"automated,omitempty"`
	Manual    []string `json:"manual,omitempty"`
}
