use crate::agent::envelope::CapabilityEnvelope;
use crate::agent::model_policy::ModelPolicy;
use crate::agent::profile::{AgentProfile, ContextPolicy, TerminationPolicy};
use crate::agent::registry::RoleDefinition;
use crate::kernel::plan::{CapabilityAccessMode, CapabilityRequirement, VerificationStrategy};
use crate::prompt::{MissionStage, PromptReference};
use crate::state_machine::agent::{AgentRole, ROLE_ALIASES};

fn model_policy(min_context_tokens: usize, temperature_millicelsius: u32) -> ModelPolicy {
    ModelPolicy {
        min_context_tokens,
        supports_tool_calling: true,
        preferred_model: crate::agent::profile::DEFAULT_PREFERRED_MODEL.to_string(),
        fallback_models: vec![crate::agent::profile::DEFAULT_FALLBACK_MODEL.to_string()],
        temperature_millicelsius,
    }
}

fn context_policy(default_max_tokens: usize, reserved: usize, threshold: u8) -> ContextPolicy {
    ContextPolicy {
        default_max_tokens,
        reserved_headroom_tokens: reserved,
        compaction_threshold_percent: threshold,
    }
}

fn termination_policy(stall: u64, wall: u64, failures: u32) -> TerminationPolicy {
    TerminationPolicy {
        step_stall_timeout_secs: stall,
        task_wall_clock_timeout_secs: wall,
        max_consecutive_action_failures: failures,
    }
}

fn read_caps(caps: &[&str]) -> CapabilityEnvelope {
    CapabilityEnvelope::read_only(caps.iter().map(|s| s.to_string()))
}

fn write_caps(caps: &[&str]) -> CapabilityEnvelope {
    CapabilityEnvelope::workspace_write(caps.iter().map(|s| s.to_string()))
}

fn full_caps(caps: &[&str]) -> CapabilityEnvelope {
    CapabilityEnvelope::full_workspace(caps.iter().map(|s| s.to_string()))
}

fn cap(id: &str, mode: CapabilityAccessMode) -> CapabilityRequirement {
    CapabilityRequirement::new(id, mode)
}

/// Helper building one built-in definition from transcribed profile data.
#[allow(clippy::too_many_arguments)]
fn builtin_def(
    id: &str,
    description: &str,
    prompt_version: u32,
    stage: MissionStage,
    researcher_class: bool,
    read_only_verification: bool,
    write_tools_permitted: bool,
    requires_modification: bool,
    default_verification: VerificationStrategy,
    default_capabilities: Vec<CapabilityRequirement>,
    concurrency_limit: Option<usize>,
    profile_id: &str,
    model_policy: ModelPolicy,
    capability_policy: CapabilityEnvelope,
    sandbox_policy: &str,
    context_policy: ContextPolicy,
    max_steps: u32,
    termination_policy: TerminationPolicy,
) -> RoleDefinition {
    let role = AgentRole::new(id);
    let aliases: Vec<String> = ROLE_ALIASES
        .iter()
        .filter(|(_, canonical)| *canonical == id)
        .map(|(alias, _)| alias.to_string())
        .filter(|alias| alias != id)
        .collect();
    RoleDefinition {
        id: role.clone(),
        description: description.to_string(),
        aliases,
        prompt_contract: format!("agent.{id}"),
        prompt_version,
        stage,
        researcher_class,
        read_only_verification,
        write_tools_permitted,
        requires_modification,
        default_verification,
        default_capabilities,
        concurrency_limit,
        profile: AgentProfile {
            id: profile_id.to_string(),
            role,
            description: description.to_string(),
            model_policy,
            capability_policy,
            sandbox_policy: sandbox_policy.to_string(),
            context_policy,
            max_steps,
            termination_policy,
            prompt_ref: PromptReference::new(format!("agent.{id}"), prompt_version),
            additional_instructions: None,
        },
    }
}

fn core_roles() -> Vec<RoleDefinition> {
    use CapabilityAccessMode::{Read, ReadWrite, Write};
    vec![
        builtin_def(
            "planner",
            "Interprets mission, decomposes work, derives candidate DAG",
            1,
            MissionStage::Plan,
            false,
            false,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-planner-v1",
            model_policy(8192, 200),
            read_caps(&["repo.read", "fs.read", "artifacts.read", "plan.propose"]),
            "read_only",
            context_policy(8192, 1536, 85),
            20,
            termination_policy(60, 600, 3),
        ),
        builtin_def(
            "researcher",
            "Explores codebase, documentation, dependencies, and architectural patterns",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-researcher-v1",
            model_policy(16384, 200),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "docs.search",
                "web.search",
            ]),
            "read_only",
            context_policy(16384, 2048, 80),
            30,
            termination_policy(60, 900, 3),
        ),
        builtin_def(
            "architect",
            "Designs system architecture, defines interfaces, data structures, and ADR contracts",
            1,
            MissionStage::Plan,
            false,
            false,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            Some(2),
            "builtin-architect-v1",
            model_policy(12288, 100),
            read_caps(&["repo.read", "fs.read", "artifacts.read", "spec.propose"]),
            "read_only",
            context_policy(12288, 2048, 80),
            20,
            termination_policy(60, 600, 3),
        ),
        builtin_def(
            "implementer",
            "Executes code modifications, runs tests, and produces artifacts",
            2,
            MissionStage::Execute,
            false,
            false,
            true,
            true,
            VerificationStrategy::Compilation,
            vec![
                cap("fs.read", Read),
                cap("fs.write", Write),
                cap("cargo.test", ReadWrite),
            ],
            Some(4),
            "builtin-implementer-v2",
            model_policy(8192, 100),
            full_caps(&[
                "fs.write",
                "fs.read",
                "workspace_fs_write",
                "workspace_fs_read",
                "shell.exec",
                "compiler_exec",
                "artifacts.write",
                "cargo.check",
                "cargo.test",
                "test_runner",
                "git_ops",
                "repo_index",
            ]),
            "workspace_write",
            context_policy(8192, 2048, 80),
            30,
            termination_policy(60, 300, 4),
        ),
        builtin_def(
            "reviewer",
            "Reviews code changes, analyzes safety, conventions, and security invariants",
            2,
            MissionStage::Review,
            false,
            false,
            false,
            false,
            VerificationStrategy::ReviewGate {
                reviewer_role: Some(AgentRole::reviewer()),
            },
            vec![cap("fs.read", Read)],
            Some(2),
            "builtin-reviewer-v2",
            model_policy(12288, 100),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "diff.analyze",
                "review.submit",
            ]),
            "read_only",
            context_policy(12288, 2048, 85),
            15,
            termination_policy(45, 450, 3),
        ),
        builtin_def(
            "verifier",
            "Executes test suites, verifies acceptance criteria, and collects completion evidence",
            2,
            MissionStage::ImplVerify,
            false,
            false,
            false,
            false,
            VerificationStrategy::Compilation,
            vec![
                cap("fs.read", Read),
                cap("cargo.test", ReadWrite),
                cap("evidence.record", ReadWrite),
            ],
            Some(2),
            "builtin-verifier-v2",
            model_policy(8192, 50),
            write_caps(&[
                "repo.read",
                "fs.read",
                "workspace_fs_read",
                "artifacts.read",
                "shell.exec",
                "proc.exec",
                "compiler_exec",
                "cargo.test",
                "test_runner",
                "evidence.record",
            ]),
            "workspace_verify",
            context_policy(8192, 1536, 85),
            15,
            termination_policy(60, 600, 3),
        ),
        builtin_def(
            "diagnostician",
            "Diagnoses failures, inspects stack traces, and produces root cause analysis",
            2,
            MissionStage::Diagnose,
            false,
            true,
            false,
            false,
            VerificationStrategy::Compilation,
            vec![cap("fs.read", Read)],
            None,
            "builtin-diagnostician-v2",
            model_policy(12288, 100),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "logs.inspect",
                "diagnosis.propose",
            ]),
            "read_only",
            context_policy(12288, 2048, 80),
            25,
            termination_policy(60, 750, 3),
        ),
        builtin_def(
            "integrator",
            "Integrates subcomponents, reconciles branch states, and validates system coherence",
            1,
            MissionStage::Ship,
            false,
            false,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            Some(2),
            "builtin-integrator-v1",
            model_policy(8192, 100),
            full_caps(&[
                "fs.write",
                "fs.read",
                "shell.exec",
                "git.merge",
                "cargo.check",
                "cargo.test",
            ]),
            "workspace_write",
            context_policy(8192, 1536, 80),
            20,
            termination_policy(60, 900, 3),
        ),
    ]
}

fn specialized_research_roles() -> Vec<RoleDefinition> {
    use CapabilityAccessMode::Read;
    vec![
        builtin_def(
            "discovery_analyst",
            "Leads Socratic project discovery, extracts problem definitions, personas, non-goals, and technical preferences",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-discovery-analyst-v1",
            model_policy(16384, 150),
            read_caps(&["repo.read", "fs.read", "artifacts.read", "docs.search"]),
            "read_only",
            context_policy(16384, 2048, 80),
            25,
            termination_policy(60, 600, 3),
        ),
        builtin_def(
            "stack_researcher",
            "Researches language editions, crate ecosystems, versions, async runtimes, and toolchains",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-stack-researcher-v1",
            model_policy(16384, 200),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "docs.search",
                "web.search",
            ]),
            "read_only",
            context_policy(16384, 2048, 80),
            30,
            termination_policy(60, 900, 3),
        ),
        builtin_def(
            "features_researcher",
            "Researches table stakes, competitive differentiators, anti-features, and user workflows",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-features-researcher-v1",
            model_policy(16384, 200),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "docs.search",
                "web.search",
            ]),
            "read_only",
            context_policy(16384, 2048, 80),
            30,
            termination_policy(60, 900, 3),
        ),
        builtin_def(
            "architecture_researcher",
            "Researches system topologies, state management, IPC/network protocols, and storage schemas",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-architecture-researcher-v1",
            model_policy(16384, 200),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "docs.search",
                "web.search",
            ]),
            "read_only",
            context_policy(16384, 2048, 80),
            30,
            termination_policy(60, 900, 3),
        ),
        builtin_def(
            "pitfalls_researcher",
            "Researches bottlenecks, concurrency hazards, upstream bugs, deprecations, and anti-patterns",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-pitfalls-researcher-v1",
            model_policy(16384, 200),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "docs.search",
                "web.search",
            ]),
            "read_only",
            context_policy(16384, 2048, 80),
            30,
            termination_policy(60, 900, 3),
        ),
        builtin_def(
            "security_researcher",
            "Researches auth models, permission checks, crypto requirements, sandboxing, and attack surfaces",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-security-researcher-v1",
            model_policy(16384, 200),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "docs.search",
                "web.search",
            ]),
            "read_only",
            context_policy(16384, 2048, 80),
            30,
            termination_policy(60, 900, 3),
        ),
        builtin_def(
            "deployment_researcher",
            "Researches process supervisors, systemd units, container packaging, and resource bounds",
            1,
            MissionStage::Research,
            true,
            true,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-deployment-researcher-v1",
            model_policy(16384, 200),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "docs.search",
                "web.search",
            ]),
            "read_only",
            context_policy(16384, 2048, 80),
            30,
            termination_policy(60, 900, 3),
        ),
    ]
}

fn governance_roles() -> Vec<RoleDefinition> {
    use CapabilityAccessMode::{Read, Write};
    vec![
        builtin_def(
            "synthesizer",
            "Reconciles multi-dimensional research findings, resolves tradeoffs, and emits SUMMARY.md and research artifacts",
            1,
            MissionStage::Synthesize,
            false,
            false,
            true,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read), cap("fs.write", Write)],
            None,
            "builtin-synthesizer-v1",
            model_policy(24576, 100),
            full_caps(&[
                "repo.read",
                "fs.read",
                "fs.write",
                "artifacts.read",
                "artifacts.write",
                "spec.propose",
            ]),
            "workspace_write",
            context_policy(24576, 4096, 80),
            20,
            termination_policy(60, 600, 3),
        ),
        builtin_def(
            "auditor",
            "Audits codebase architecture, production reachability, authority duplication, and consistency",
            2,
            MissionStage::Review,
            false,
            false,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-auditor-v1",
            model_policy(32768, 100),
            read_caps(&["repo.read", "fs.read", "artifacts.read", "git.read"]),
            "read_only",
            context_policy(32768, 4096, 80),
            25,
            termination_policy(90, 900, 3),
        ),
        builtin_def(
            "release_certifier",
            "Certifies release readiness across the 20-point production evidence matrix",
            2,
            MissionStage::Ship,
            false,
            false,
            false,
            false,
            VerificationStrategy::ArtifactInspection { paths: Vec::new() },
            vec![cap("fs.read", Read)],
            None,
            "builtin-release-certifier-v1",
            model_policy(32768, 100),
            read_caps(&[
                "repo.read",
                "fs.read",
                "artifacts.read",
                "git.read",
                "qa.test",
            ]),
            "read_only",
            context_policy(32768, 4096, 80),
            25,
            termination_policy(90, 900, 3),
        ),
    ]
}

/// The 18 built-in role definitions, transcribed from the pre-27.5
/// `AgentProfile::built_in` match (single authority since 27.5).
pub(super) fn builtin_role_definitions() -> Vec<RoleDefinition> {
    let mut defs = core_roles();
    defs.extend(specialized_research_roles());
    defs.extend(governance_roles());
    defs
}
