name: PR - Benchmark

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: pr-benchmark-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    if: contains(github.event.pull_request.labels.*.name, 'benchmark')
    uses: ./.github/workflows/benchmarks.yml
    secrets: inherit
